Add I2c HILS test tutorial
ut-issl/s2e-documents pull request #18
Opened 2022-03-02 23:38 UTC by seki-hiro

## Overview
The tutorial for HILS testing of emulated I2C components are added.

## Issue
https://github.com/ut-issl/s2e-core/issues/30

## Details
Hardware configuration and software setup for HILS testing of emulated I2C components are shown.

##  Validation results
Validation results are written on the page.

## Scope of influence
The behavior of HILS tutorial will be change.

## Supplement
Related pull request : https://github.com/ut-issl/s2e-core/pull/31

## Note
**TODO** The supported s2e-core version of I2C HILS test should be added after https://github.com/ut-issl/s2e-core/pull/31 is merged.

2022-03-07 13:01 UTC, 200km requested changes
コメントつけました。

2022-03-07 13:01 UTC, 200km commented on Tutorials/HowToUseSerialPortCommunication.md
> +  - If the comment `Error: the specified step_sec is too small for this computer.` appears, comment out it in `s2e-core/src/Environment/Global/SimTime.cpp`.
[Q] ここは、コメントアウトを推奨するのが正しいんですかね？どちらかというと、コンポの実行頻度などをゆっくりするほうが良い気もしますが。

2022-03-14 08:57 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +  - **Note** Currently, the latency from the time the I2C-USB converter receives the data via I2C communication to the time it is sent to the I2c target component via serial communication is large, m
修正しました

2022-03-14 09:36 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +  - Set loopback connection of a I2C-USB controller converter and a I2C-USB target converter using two USB ports of your computer.<img src="./figs/SerialPortCommunication_I2CLoopback.png" alt="Serial
修正しました。

2022-03-14 09:36 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +  - **Note** Loopback is not always necessary. Only one of the I2C controller or I2C target can be simulated in S2E.
追記しました。

2022-03-14 09:36 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +## 4. Sample codes for I2C communication
特にこだわりがあるわけではありませんが、前半部分の説明はUARTとI2Cとで共通しているので、同一ファイルでも良いかという気がしています。

2022-03-14 09:36 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +   - Edit the constructor's argument based on the COM port number checked above.
追記しました。

2022-03-14 09:36 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +- Hardware Settings
追記しました。

2022-03-14 09:36 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +    - Three frames of telemetry is stored in the I2C-USB converter (target) in advance.
修正しました。

2022-03-14 09:36 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +  -  The data sent by the target and the data received by the controller are the outputs. Since there are three frames accumulated in the converter,  the controller is receiving telemetry that was se
ありがとうございます。修正しました。

2022-03-14 09:36 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +  - If the comment `Error: the specified step_sec is too small for this computer.` appears, comment out it in `s2e-core/src/Environment/Global/SimTime.cpp`.
PCのスペック的に、想定する速度では実行できていないということなので、

> コンポの実行頻度などをゆっくりするほうが良い

と思いました。修正したいと思います。

2022-03-14 09:37 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +    - Each time the telemetry stored in converter is read by the I2C read commnad, the telemetry is added from the target component.
能動体で書き直しました。

2022-03-14 09:37 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +  - s2e-core: TBD
最新developと書いておきます。

2022-03-14 13:42 UTC, 200km commented on Tutorials/HowToUseSerialPortCommunication.md
> +## 4. Sample codes for I2C communication
目次でタイトルを見たときに、普通のユーザーがここにI2Cのことが書かれていると気づくかどうかが重要な気がします。  
今は目次では`How To Perform HILS Test`ですが、`How To Perform HILS Test with UART`と`How To Perform HILS Test with I2C`の２つのタイトルに分けたほうがパット見わかりやすいかなと思いました。

2022-03-14 13:42 UTC, 200km commented on Tutorials/HowToUseSerialPortCommunication.md
> +## 4. Sample codes for I2C communication
目次でタイトルを見たときに、普通のユーザーがここにI2Cのことが書かれていると気づくかどうかが重要な気がします。  
今は目次では`How To Perform HILS Test`ですが、`How To Perform HILS Test with UART`と`How To Perform HILS Test with I2C`の２つのタイトルに分けたほうがパット見わかりやすいかなと思いました。

2022-03-16 03:27 UTC, seki-hiro commented on Tutorials/HowToUseSerialPortCommunication.md
> +## 4. Sample codes for I2C communication
目次のタイトルでUART HILSとI2C HILSを選択できるようにファイルを分けました。

2022-03-16 07:25 UTC, seki-hiro commented
質問です。[SUMMARY.md](https://github.com/ut-issl/s2e-documents/blob/main/SUMMARY.md)は、どのような目的であるのでしょうか？ファイルを追加・変更した際に、[README.md](https://github.com/ut-issl/s2e-documents/blob/main/README.md)だけでなくSUMMARY.mdも変更した方がよろしいでしょうか？

2022-03-16 07:52 UTC, sksat commented
`SUMMARY.md`はMarkdownからHTMLを生成するのに使用している`mdbook`というソフトウェアが使用しているものです。そのため、(GitHub Pagesでデプロイされている)実際のドキュメントのページを更新するためにはこのファイルを編集する必要があります。

一方、`README.md`はGitHub Pagesに移行してからは使われていません。とはいえ、あるとこのリポジトリを開いたときに最初に表示されて分かりやすくはあるので残している、という状態です。かといって今後ファイルの新規追加などがある度に両方のファイルを編集するのは不毛なのでどうにかしたいですね。

2022-03-16 08:07 UTC, seki-hiro commented
ありがとうございます。GitHub Pagesについてあまり把握できていなかったのですが、SUMMARY.mdを更新していないために、”This branch has not been deployed”という表示がPRで出ていたのですね。ひとまず、`SUMMARY.md`と`README.md`の両方を更新します。

2022-03-16 12:11 UTC, sksat commented
あ，`This branch has not been deployed`に関しては，Pull Requestから直接Deployment(GitHub Pagesの更新など)は発生しないので気にしなくて大丈夫です．

2022-03-16 13:59 UTC, seki-hiro commented
了解です、ありがとうございます。

2022-03-16 15:49 UTC, 200km commented on Tutorials/HowToUseSerialPortCommunication.md
> +## 4. Sample codes for I2C communication
ありがとうございます。

2022-03-16 15:49 UTC, 200km approved these changes

2022-03-17 02:40 UTC, seki-hiro commented
approveいただいたのでマージします

2022-03-17 02:40 UTC, merged