Draft: Fix equations to suit with MathJax
ut-issl/s2e-documents pull request #23
Opened 2022-04-01 07:22 UTC by 200km

## Overview
Fix equations to suit with MathJax.

## Issue
- #13 

## Details
- `\bm` -> `\boldsymbol`
- indent for `math` and `table` are aligned

##  Validation results
Link to tests or validation results.

## Scope of influence
Limited to each document file.

## Supplement
NA

## Note
NA

2022-04-01 11:44 UTC, sksat requested changes

2022-04-01 11:44 UTC, sksat commented on Specifications/Disturbance/Spec_SurfaceForce_AirDrag.md
>        ```
ここらへん変な空白があって変換漏れしてますね
```suggestion
      ```
```

2022-04-01 11:44 UTC, sksat commented on Specifications/Disturbance/Spec_SurfaceForce_AirDrag.md
> +        ```
```suggestion
        ```
```

2022-04-01 11:57 UTC, 200km commented
ありがとうございます。空白消しておきます。

今困っているのが、CelestialRotationの中にある下記の部分で、行列表のの途中で行頭にマイナスが入ると、それがmdの箇条書きみたいに見做されてそれ以降の数式が死ぬという部分です。
-sinをかっこで括ると正常に表示されるのですが。。。
```
\bf{P} = 
    \begin{pmatrix}
    \cos{(-z)} & \sin{(-z)} & 0 \\
    - \sin{(-z)} & \cos{(-z)} & 0 \\
    0 & 0 & 1
    \end{pmatrix}
```

2022-04-01 12:11 UTC, sksat commented on Specifications/Environment/Spec_CelestialRotation.md
> +      \end{pmatrix}
```suggestion
      \begin{pmatrix}
      \cos{(-z)} & \sin{(-z)} & 0 \\
      \- \sin{(-z)} & \cos{(-z)} & 0 \\
      0 & 0 & 1
      \end{pmatrix}
      \begin{pmatrix}
      \cos{\theta} & 0 & - \sin{\theta} \\
      0 & 1 & 0 \\
      \sin{\theta} & 0 & \cos{\theta}
      \end{pmatrix}
      \begin{pmatrix}
      \cos{(-\zeta)} & \sin{(-\zeta)} & 0  \\
      \- \sin{(-\zeta)} & \cos{(-\zeta)} & 0 \\
      0 & 0 & 1
      \end{pmatrix}
```

これで大丈夫そうです

2022-04-02 21:30 UTC, 200km commented
Approveもらいましたが、Attitude Dynamicsも色々問題があったので修正しました。  
手元ではきれいに表示できているので、問題ないと思いますのでマージします。

2022-04-02 21:30 UTC, merged